twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        company_util: '@App\Service\CompanyUtils'
        car_util: '@App\Service\CarUtils'
when@test:
    twig:
        strict_variables: true
