<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'da97d3c81b27a197fe89172fb8112f31',
  'DATABASE_URL' => 'mysql://b310fc038ee88e:0c67e114@eu-cluster-west-01.k8s.cleardb.net:3306/heroku_5de4763d44b212c',
  'MAILER_DSN' => 'smtp://845ff3d236de12:57a1cc6173e40b@sandbox.smtp.mailtrap.io:2525',
);
